# Site settings
title: David John Wilson
email: mrdavidjwilson@gmail.com
description: > #
  A personal website for David John Wilson.
  Includes information about data science, research, and ballet
  reviews.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.davidjw.co.uk" # the base hostname & protocol for your site
github_username:  davidjohnwilson

# Build settings
markdown: kramdown
